export default {
    MOMENT: 'MOMENT',
    MONGO_MODELS: 'MONGO_MODELS',
    MONGO_CONNECTION: 'MONGO_CONNECTION',
    API_ERROR: 'API_ERROR',
    CONFIGS: 'CONFIGS',
    JWT: 'JWT',
    PAGINATE: 'PAGINATE',
    BCRYPT: 'BCRYPT',
    AUTH_SERVICE: 'AUTH_SERVICE',
    CRYPT_SERVICE: 'CRYPT_SERVICE',
    JWT_SERVICE: 'JWT_SERVICE',
    USER_SERVICE: 'USER_SERVICE',
}
  