export default {
    NO_CONTENT: 'NO_CONTENT',
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    NOT_FOUND: 'NOT_FOUND',
    DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
    INTERNAL_SERVER: 'INTERNAL_SERVER'
  }
  