export default {
  RESPONSE_BAD_REQUEST: 'RESPONSE_BAD_REQUEST',
  RESPONSE_UNATHORIZED: 'RESPONSE_UNATHORIZED',
  RESPONSE_INTERNAL_ERROR: 'RESPONSE_INTERNAL_ERROR',
  RESPONSE_NO_CONTENT: 'RESPONSE_NO_CONTENT',
  
  ERROR_UNKNOWN: 'ERROR_UNKNOWN',
  
  AUTH_ERROR_CREATE_USER: 'AUTH_ERROR_CREATE_USER',
  
  VALIDATION_IS_EMPTY: 'VALIDATION_IS_EMPTY',
  VALIDATION_MUST_BE: 'VALIDATION_MUST_BE',
  VALIDATION_MUST_BE_NUMERIC: 'VALIDATION_MUST_BE_NUMERIC',
  VALIDATION_MUST_BE_DIGITS: 'VALIDATION_MUST_BE_DIGITS',
  VALIDATION_MUST_BE_UPPERCASE: 'VALIDATION_MUST_BE_UPPERCASE',
  
  VALIDATION_MUST_BE_VALID_DATE_FORMAT: 'VALIDATION_MUST_BE_VALID_DATE_FORMAT',
  VALIDATION_MUST_BE_VALID_FORMAT: 'VALIDATION_MUST_BE_VALID_FORMAT',
  VALIDATION_MUST_BE_VALID_PHONE: 'VALIDATION_MUST_BE_VALID_PHONE',
  VALIDATION_MUST_BE_VALID_LANG_CODE: 'VALIDATION_MUST_BE_VALID_LANG_CODE',
  VALIDATION_MUST_BE_VALID_COUNTRY_CODE: 'VALIDATION_MUST_BE_VALID_COUNTRY_CODE',
  VALIDATION_IS_INVALID_OR_EXPIRED: 'VALIDATION_IS_INVALID_OR_EXPIRED',
  
  VALIDATION_ALREADY_EXISTS: 'VALIDATION_ALREADY_EXISTS',
  VALIDATION_IS_NOT_EXISTS: 'VALIDATION_IS_NOT_EXISTS',
  VALIDATION_IS_NOT_YOURS: 'VALIDATION_IS_NOT_YOURS',
  VALIDATION_IS_NOT_VALID_VALUE: 'VALIDATION_IS_NOT_VALID_VALUE'
}
  